name: weather_app
description: "A mobile app that shows current weather and predicts weather for coming days."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.2+1
  get_it: ^8.0.3
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  envied: ^0.5.4+1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4+1

flutter_native_splash:
  image: "assets/images/splash_logo.png"
  color: "#007DC3"
  android_12:
    color: "#007DC3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#ffffff"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Laila
      fonts:
        - asset: assets/fonts/Laila-Light.ttf
          weight: 300
        - asset: assets/fonts/Laila-Regular.ttf
          weight: 400
        - asset: assets/fonts/Laila-Medium.ttf
          weight: 500
        - asset: assets/fonts/Laila-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Laila-Bold.ttf
          weight: 700